import type { Metadata } from 'next';
import './globals.css';

export const metadata: Metadata = {
  title: 'Awesome 3D Prompts · Gallery',
  description:
    'Browse every 3D model generated by the Awesome 3D Prompts collection — preview GLB files in the browser and copy the prompts that produced them.',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="zh-CN">
      <body className="min-h-screen font-sans">{children}</body>
    </html>
  );
}
